export const AUTHENTICATE = 'AUTHENTICATE';
export const AUTH_ERROR = 'AUTH_FINISHED';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';

export const APP_START_AUTH = 'APP_START_AUTH';
export const APP_START_AUTH_ERROR = 'APP_START_AUTH_ERROR';
export const APP_START_AUTH_SUCCESS = 'APP_START_AUTH_SUCCESS';

export const SAVE_TOKEN = 'SAVE_TOKEN';

export const WITH_AUTHENTICATION = 'WITH_AUTHENTICATION';

export const REFRESH_TOKENS_ERROR = 'REFRESH_TOKENS_ERROR';
export const REFRESH_TOKENS_ERROR_HANDLED = 'REFRESH_TOKENS_ERROR_HANDLED';

export const UNLOGIN = 'UNLOGIN';
