export const GET_DIAGRAMS_PREVIEWS = 'GET_DIAGRAMS_PREVIEWS';
export const GET_DIAGRAMS_PREVIEWS_SUCCESS = 'GET_DIAGRAMS_PREVIEWS_SUCCESS';
export const GET_DIAGRAMS_PREVIEWS_ERROR = 'GET_DIAGRAMS_PREVIEWS_ERROR';

export const DELETE_DIAGRAM = 'DELETE_DIAGRAM';
export const DELETE_DIAGRAM_SUCCESS = 'DELETE_DIAGRAM_SUCCESS';
export const DELETE_DIAGRAM_ERROR = 'DELETE_DIAGRAM_ERROR';

export const CREATE_DIAGRAM = 'CREATE_DIAGRAM';
export const CREATE_DIAGRAM_SUCCESS = 'CREATE_DIAGRAM_SUCCESS';
export const CREATE_DIAGRAM_ERROR = 'CREATE_DIAGRAM_ERROR';

export const GET_DIAGRAM_FILE_ERROR = 'GET_DIAGRAM_FILE_ERROR';
export const GET_DIAGRAM_FILE_SUCCESS = 'GET_DIAGRAM_FILE_SUCCESS';

export const SELECT_DIAGRAM = 'SELECT_DIAGRAM';
