export const GET_DIAGRAMS_PREVIEWS = 'GET_DIAGRAMS_PREVIEWS';
export const GET_DIAGRAMS_PREVIEWS_SUCCESS = 'GET_DIAGRAMS_PREVIEWS_SUCCESS';
export const GET_DIAGRAMS_PREVIEWS_ERROR = 'GET_DIAGRAMS_PREVIEWS_ERROR';

export const DELETE_DIAGRAM = 'DELETE_DIAGRAM';
export const DELETE_DIAGRAM_SUCCESS = 'DELETE_DIAGRAM_SUCCESS';
export const DELETE_DIAGRAM_ERROR = 'DELETE_DIAGRAM_ERROR';
export const DELETE_DIAGRAM_FORGET = 'DELETE_DIAGRAM_FORGET';
