export const GET_DIAGRAMS_PREVIEWS = 'GET_DIAGRAMS_PREVIEWS';
export const GET_DIAGRAMS_PREVIEWS_SUCCESS = 'GET_DIAGRAMS_PREVIEWS_SUCCESS';
export const GET_DIAGRAMS_PREVIEWS_ERROR = 'GET_DIAGRAMS_PREVIEWS_ERROR';
export const GET_DIAGRAMS_PREVIEWS_FORGET = 'GET_DIAGRAMS_PREVIEWS_FORGET';
